// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUMPxAJwDIK-gQo1-DYeIhUa6KfaIDwk',
    appId: '1:345017882777:web:e11215466fdb2a5a36c008',
    messagingSenderId: '345017882777',
    projectId: 'kgis-mobile-906a0',
    authDomain: 'kgis-mobile-906a0.firebaseapp.com',
    storageBucket: 'kgis-mobile-906a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoyTa3Bl4Qm9DPlYDkYn0vacS3ZFBarro',
    appId: '1:345017882777:android:729a416a1064449036c008',
    messagingSenderId: '345017882777',
    projectId: 'kgis-mobile-906a0',
    storageBucket: 'kgis-mobile-906a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1o54rMR2LZoUcR0xU_dy5bA6c297USY',
    appId: '1:345017882777:ios:40394fd7aff6c66f36c008',
    messagingSenderId: '345017882777',
    projectId: 'kgis-mobile-906a0',
    storageBucket: 'kgis-mobile-906a0.appspot.com',
    iosClientId: '345017882777-eal5rnis42dmfgiur6k309e2uvpp7s9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.kgisMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1o54rMR2LZoUcR0xU_dy5bA6c297USY',
    appId: '1:345017882777:ios:5ea6bc5238fd756436c008',
    messagingSenderId: '345017882777',
    projectId: 'kgis-mobile-906a0',
    storageBucket: 'kgis-mobile-906a0.appspot.com',
    iosClientId: '345017882777-3d3vmutnu5ga0odlop9403nv381h19i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kgisMobile.RunnerTests',
  );
}
